# Generated by Django 4.1.7 on 2023-03-23 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobanco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('tipo_conta', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('tipo_conta', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobanco.contageral')),
            ],
        ),
        migrations.AddField(
            model_name='contageral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobanco.usuario'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('id_saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobanco.saldo')),
            ],
        ),
    ]
