# Generated by Django 4.1.7 on 2023-03-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaGeral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('tipo_conta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('tipo_conta', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_aplicativo.contageral')),
            ],
        ),
        migrations.AddField(
            model_name='contageral',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_aplicativo.usuario'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('id_saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_aplicativo.saldo')),
            ],
        ),
    ]
